### ISSUE TITLE
Add gain and range setting

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_SI1145#11]
Re this thread:
https://forums.adafruit.com/viewtopic.php?p=938230#p938230

Add ability to get/set the various gain and range settings.

**Comment by aaronwmorris** [comment]
I have submitted PR #21 which includes the gain and high range setting.

**Comment by jposada202020** [comment]
@FoamyGuy I think this can be closed now :) after PR 21

**Comment by aaronwmorris** [comment]
I agree, everything is working as expected.

**Comment by caternuson** [comment]
Closing. Should be resolved by #21.
