### ISSUE TITLE
Error code getting masked out

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_SI1145#13]
This is a minor big. The mask here should be removed:
https://github.com/adafruit/Adafruit_CircuitPython_SI1145/blob/4b44479fe55e5d479b77ece46478ae04c1afe2a7/adafruit_si1145.py#L165

Masking the upper 4 bits is useful to detect if there is an error. But the actual error is then coded into the lower 4 bits. So the print should just not mask anything and print the whole response value.
![image](https://user-images.githubusercontent.com/8755041/186712566-20543dce-54db-4ee8-815f-8134450c20aa.png)

**Comment by sokratisvas** [comment]
I would like to help.
